# testing environment

master-compose-deploy:
  stage: deploy
  script:
  - ssh compose@composesshd /srv/tools/id-compose/
  only:
  - master
  tags:
  - master

master-tagged-compose-deploy:
  stage: deploy
  script:
  - ssh compose@composesshd /srv/tools/id-compose/
  only:
  - tags
  tags:
  - production
