stages:
  - build
  - test
  - migrate
  - deploy

build:
  stage: build
  script:
    - sudo -E /occrp/scripts/id/build.sh
  tags:
    - zam

test:
  stage: test
  script:
    - sudo -E /occrp/scripts/id/test.sh
  tags:
    - zam

deploy-test:
  stage: deploy
  script:
    # - sudo -E /occrp/scripts/id/migrate.sh
    - sudo -E /occrp/scripts/id/deploy.sh
  environment:
    name: test-id
    url: https://test.id.occrp.org
  when: manual
  tags:
    - zam

deploy-prod:
  stage: deploy
  script:
    # - sudo -E /occrp/scripts/id/migrate.sh
    - sudo -E /occrp/scripts/id/deploy.sh
  environment:
    name: id
    url: https://id-2.occrp.org
  only:
    - master
  when: manual
  tags:
    - zam
