version: '3.4'

x-build:
  &default-build
  image: id/api
  build:
    context: .
    args:
      - "ID_VERSION=${ID_VERSION}"
  environment:
    - DJANGO_SECRET_KEY=local
    - MEDIA_ROOT=/tmp

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - ".build/data/postgres:/var/lib/postgresql/data"
      - ".build/logs/postgres:/var/log"
    environment:
      POSTGRES_PASSWORD: 'postgres'

  queue:
    << : *default-build
    restart: always
    command: >
      sh -c "pip install -r requirements-testing.txt && python manage.py queue"
    volumes:
      - ./:/id
    depends_on:
      - postgres

  api:
    << : *default-build
    restart: always
    command: >
      sh -c "pip install -r requirements-testing.txt &&
             python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./:/id
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  web:
    image: nginx:1.17.8-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    depends_on:
      - api
